### ISSUE TITLE
[Feature Request] bring plugin to mobile

### ISSUE THREAD

**Issue by LePenseur13** [No-Instructions/Relay#1]
Personal Use Case:
collaboration is the main feature missing in Obsidian. 
about 80% of my Obsidian use is Ipad and Phone. It would be amazing if I could collaborate there with other people on projects within Obsidian.

I know this is probably a ton of work, if even possible, but I would appreciate the effort.

**Comment by dtkav** [comment]
Hey @LePenseur13 --

If you are comfortable testing the beta version then you can install it on mobile.
I personally use it on android, and have gotten it to work on iOS with some quirks.

The reason we haven't rolled it out more broadly is that iOS user experience is pretty broken in the login flow.
I'm working on that actively.

If you're interested in testing on mobile but don't know how to use BRAT (for beta testing), feel free to [join our Discord](https://discord.gg/mgtWWXRbcF) and we'll help you out.

**Comment by dtkav** [comment]
Here are the instructions for using BRAT (copied from the README)

## Installing the latest Beta Release

BRAT is the **Beta Reviewer's Auto-update Tool for Obsidian**.

### 1. Install BRAT

First we need to install the Obsidian Plugin [BRAT](https://github.com/TfTHacker/obsidian42-brat). If you haven't yet enabled community plugins, you can follow [this guide](https://help.obsidian.md/Extending+Obsidian/Community+plugins) on help.obsidian.md.

Search for "BRAT" and install the plugin by TfTHacker.

### 2. Add Relay via BRAT

-   Once you have BRAT installed open the Settings pane by pressing on the great in the bottom left of Obsidian.
    -   In Settings, navigate to BRAT under "community plugins" at the bottom of the right-hand section.
    -   In the BRAT configuration page click "Add Beta plugin".
        -   Enter in `No-Instructions/Relay`.
        -   Ensure that `Enable after installing the plugin` is checked.
        -   Click `Add Plugin`

**Comment by sonikun** [comment]
+1 for iPad support!

**Comment by dtkav** [comment]
Relay 0.4.0 now supports mobile!

cc: @LePenseur13 @sonikun

**Comment by LePenseur13** [comment]
Thank you. Awesome

**Comment by ShadowDrakken** [comment]
I'm sorry, but this doesn't actually appear to be working. 0.4.1 on iOS only syncs the title and not the content when syncing from desktop to iOS. Syncs fine from iOS to iOS though oddly enough.
